packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - core-js-pure
  - cpu-features
  - esbuild
  - oxc-resolver
  - sharp
  - sqlite3
  - ssh2
