/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "abouts": [],
    "web-services": [],
    "web-contacts": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "blogs.index": [],
    "blogs.show": [
        {
            "name": "blog",
            "required": true,
            "binding": "slug"
        }
    ],
    "blogs.create": [],
    "blogs.store": [],
    "blogs.edit": [
        {
            "name": "blog",
            "required": true,
            "binding": "id"
        }
    ],
    "blogs.update": [
        {
            "name": "blog",
            "required": true,
            "binding": "id"
        }
    ],
    "blogs.destroy": [
        {
            "name": "blog",
            "required": true,
            "binding": "id"
        }
    ],
    "blogs.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "blogs.trash": [],
    "blogs.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contacts.search": [],
    "contact-types.index": [],
    "contact-types.create": [],
    "contact-types.store": [],
    "contact-types.edit": [
        {
            "name": "contact_type",
            "required": true
        }
    ],
    "contact-types.update": [
        {
            "name": "contact_type",
            "required": true
        }
    ],
    "contact-types.destroy": [
        {
            "name": "contact_type",
            "required": true
        }
    ],
    "contact-types.trash": [],
    "contact-types.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contact-types.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contacts.index": [],
    "contacts.create": [],
    "contacts.store": [],
    "contacts.show": [
        {
            "name": "contact",
            "required": true,
            "binding": "id"
        }
    ],
    "contacts.edit": [
        {
            "name": "contact",
            "required": true,
            "binding": "id"
        }
    ],
    "contacts.update": [
        {
            "name": "contact",
            "required": true,
            "binding": "id"
        }
    ],
    "contacts.destroy": [
        {
            "name": "contact",
            "required": true,
            "binding": "id"
        }
    ],
    "contacts.trash": [],
    "contacts.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contacts.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_inwards.index": [],
    "service_inwards.create": [],
    "service_inwards.store": [],
    "service_inwards.show": [
        {
            "name": "service_inward",
            "required": true
        }
    ],
    "service_inwards.edit": [
        {
            "name": "service_inward",
            "required": true
        }
    ],
    "service_inwards.update": [
        {
            "name": "service_inward",
            "required": true
        }
    ],
    "service_inwards.destroy": [
        {
            "name": "service_inward",
            "required": true
        }
    ],
    "service_inwards.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_inwards.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_inwards.trash": [],
    "test.inertia": [],
    "service_inwards.nextRma": [],
    "service_inwards.search": [],
    "job_cards.index": [],
    "job_cards.create": [],
    "job_cards.store": [],
    "job_cards.show": [
        {
            "name": "job_card",
            "required": true
        }
    ],
    "job_cards.edit": [
        {
            "name": "job_card",
            "required": true
        }
    ],
    "job_cards.update": [
        {
            "name": "job_card",
            "required": true
        }
    ],
    "job_cards.destroy": [
        {
            "name": "job_card",
            "required": true
        }
    ],
    "jobcards.search": [],
    "job_cards.trash": [],
    "job_cards.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "job_cards.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_statuses.index": [],
    "service_statuses.create": [],
    "service_statuses.store": [],
    "service_statuses.show": [
        {
            "name": "service_status",
            "required": true
        }
    ],
    "service_statuses.edit": [
        {
            "name": "service_status",
            "required": true
        }
    ],
    "service_statuses.update": [
        {
            "name": "service_status",
            "required": true
        }
    ],
    "service_statuses.destroy": [
        {
            "name": "service_status",
            "required": true
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.trash": [],
    "users.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "job_assignments.index": [],
    "job_assignments.create": [],
    "job_assignments.store": [],
    "job_assignments.edit": [
        {
            "name": "job_assignment",
            "required": true
        }
    ],
    "job_assignments.update": [
        {
            "name": "job_assignment",
            "required": true
        }
    ],
    "job_assignments.destroy": [
        {
            "name": "job_assignment",
            "required": true
        }
    ],
    "job_assignments.kanban": [],
    "job_assignments.position": [
        {
            "name": "assignment",
            "required": true
        }
    ],
    "job_assignments.service": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.start_service": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.complete_service": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.ready": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.deliver": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.generateOtp": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.confirmDelivery": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.close": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.audit": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.close_admin": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "job_assignments.finals": [],
    "job_assignments.show": [
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "service_parts.index": [],
    "service_parts.create": [],
    "service_parts.store": [],
    "service_parts.edit": [
        {
            "name": "service_part",
            "required": true
        }
    ],
    "service_parts.update": [
        {
            "name": "service_part",
            "required": true
        }
    ],
    "service_parts.destroy": [
        {
            "name": "service_part",
            "required": true
        }
    ],
    "service_parts.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_parts.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_parts.trash": [],
    "job_spare_requests.index": [],
    "job_spare_requests.create": [],
    "job_spare_requests.store": [],
    "job_spare_requests.edit": [
        {
            "name": "job_spare_request",
            "required": true
        }
    ],
    "job_spare_requests.update": [
        {
            "name": "job_spare_request",
            "required": true
        }
    ],
    "job_spare_requests.destroy": [
        {
            "name": "job_spare_request",
            "required": true
        }
    ],
    "job_spare_requests.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "job_spare_requests.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "job_spare_requests.trash": [],
    "service_parts.images.store": [
        {
            "name": "servicePart",
            "required": true,
            "binding": "id"
        }
    ],
    "service_parts.images.primary": [
        {
            "name": "servicePart",
            "required": true
        },
        {
            "name": "image",
            "required": true,
            "binding": "id"
        }
    ],
    "service_parts.images.destroy": [
        {
            "name": "image",
            "required": true,
            "binding": "id"
        }
    ],
    "service_parts.images.reorder": [
        {
            "name": "servicePart",
            "required": true,
            "binding": "id"
        }
    ],
    "service_parts.show": [
        {
            "name": "servicePart",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.trash": [],
    "roles.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roles.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissions.index": [],
    "permissions.create": [],
    "permissions.store": [],
    "permissions.show": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.edit": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.update": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.destroy": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.trash": [],
    "permissions.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissions.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "system.manager": [],
    "system.manager.command": [],
    "out_service_centers.index": [],
    "out_service_centers.create": [],
    "out_service_centers.store": [],
    "out_service_centers.edit": [
        {
            "name": "out_service_center",
            "required": true
        }
    ],
    "out_service_centers.update": [
        {
            "name": "out_service_center",
            "required": true
        }
    ],
    "out_service_centers.destroy": [
        {
            "name": "out_service_center",
            "required": true
        }
    ],
    "out_service_centers.show": [
        {
            "name": "outServiceCenter",
            "required": true,
            "binding": "id"
        }
    ],
    "out_service_centers.trash": [],
    "out_service_centers.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "out_service_centers.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "service_inwards.notes.store": [
        {
            "name": "serviceInward",
            "required": true,
            "binding": "id"
        }
    ],
    "service_inwards.notes.update": [
        {
            "name": "serviceInward",
            "required": true
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "service_inwards.notes.destroy": [
        {
            "name": "serviceInward",
            "required": true
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "ready_for_deliveries.index": [],
    "ready_for_deliveries.create": [],
    "ready_for_deliveries.store": [],
    "ready_for_deliveries.show": [
        {
            "name": "ready_for_delivery",
            "required": true
        }
    ],
    "ready_for_deliveries.edit": [
        {
            "name": "ready_for_delivery",
            "required": true
        }
    ],
    "ready_for_deliveries.update": [
        {
            "name": "ready_for_delivery",
            "required": true
        }
    ],
    "ready_for_deliveries.destroy": [
        {
            "name": "ready_for_delivery",
            "required": true
        }
    ],
    "ready_for_deliveries.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "ready_for_deliveries.forceDelete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "ready_for_deliveries.trash": [],
    "todos.index": [],
    "todos.create": [],
    "todos.store": [],
    "todos.edit": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todos.update": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todos.destroy": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todos.trash": [],
    "todos.restore": [
        {
            "name": "todo",
            "required": true
        }
    ],
    "todos.forceDelete": [
        {
            "name": "todo",
            "required": true
        }
    ],
    "todos.show": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todos.reorder": [],
    "todos.toggle-complete": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "calls.index": [],
    "calls.create": [],
    "calls.store": [],
    "calls.edit": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.update": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.destroy": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.show": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.trash": [],
    "calls.restore": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.forceDelete": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.search": [],
    "contacts.history": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "calls.notes.store": [
        {
            "name": "call_log",
            "required": true
        }
    ],
    "calls.notes.update": [
        {
            "name": "call_log",
            "required": true
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "calls.notes.destroy": [
        {
            "name": "call_log",
            "required": true
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "enquiries.index": [],
    "enquiries.create": [],
    "enquiries.store": [],
    "enquiries.show": [
        {
            "name": "enquiry",
            "required": true
        }
    ],
    "enquiries.edit": [
        {
            "name": "enquiry",
            "required": true
        }
    ],
    "enquiries.update": [
        {
            "name": "enquiry",
            "required": true
        }
    ],
    "enquiries.destroy": [
        {
            "name": "enquiry",
            "required": true
        }
    ],
    "messaging.channel": [],
    "messaging.whatsapp": [],
    "messaging.whatsapp.send": [],
    "messaging.chat-history": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "service_inwards.by_contact": [
        {
            "name": "contact",
            "required": true,
            "binding": "id"
        }
    ],
    "job_cards.by_contact": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "calls.quickStore": [],
    "calls.updateEnquiry": [],
    "blog.categories.index": [],
    "blog.categories.create": [],
    "blog.categories.store": [],
    "blog.categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.tags.index": [],
    "blog.tags.create": [],
    "blog.tags.store": [],
    "blog.tags.edit": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.tags.update": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.tags.destroy": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.posts.index": [],
    "blog.posts.create": [],
    "blog.posts.store": [],
    "blog.posts.edit": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.posts.update": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.posts.destroy": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.posts.images.store": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "blog.posts.images.destroy": [
        {
            "name": "image",
            "required": true
        }
    ],
    "blog.posts.images.reorder": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
