using cxserver.Modules.Common.Entities;

namespace cxserver.Modules.Common.Configurations;

internal static class LocationSeedData
{
    internal static readonly Country[] Countries =
    [
        new Country { Id = 1, Name = "-", CountryCode = "--", IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Country { Id = 2, Name = "India", CountryCode = "IN", IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Country { Id = 3, Name = "United States", CountryCode = "US", IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc }
    ];

    internal static readonly State[] States =
    [
        new State { Id = 1, Name = "-", StateCode = "-", CountryId = 1, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 2, Name = "Andhra Pradesh", StateCode = "AP", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 3, Name = "Arunachal Pradesh", StateCode = "AR", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 4, Name = "Assam", StateCode = "AS", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 5, Name = "Bihar", StateCode = "BR", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 6, Name = "Chhattisgarh", StateCode = "CG", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 7, Name = "Goa", StateCode = "GA", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 8, Name = "Gujarat", StateCode = "GJ", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 9, Name = "Haryana", StateCode = "HR", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 10, Name = "Himachal Pradesh", StateCode = "HP", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 11, Name = "Jharkhand", StateCode = "JH", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 12, Name = "Karnataka", StateCode = "KA", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 13, Name = "Kerala", StateCode = "KL", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 14, Name = "Madhya Pradesh", StateCode = "MP", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 15, Name = "Maharashtra", StateCode = "MH", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 16, Name = "Manipur", StateCode = "MN", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 17, Name = "Meghalaya", StateCode = "ML", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 18, Name = "Mizoram", StateCode = "MZ", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 19, Name = "Nagaland", StateCode = "NL", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 20, Name = "Odisha", StateCode = "OD", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 21, Name = "Punjab", StateCode = "PB", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 22, Name = "Rajasthan", StateCode = "RJ", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 23, Name = "Sikkim", StateCode = "SK", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 24, Name = "Tamil Nadu", StateCode = "TN", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 25, Name = "Telangana", StateCode = "TS", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 26, Name = "Tripura", StateCode = "TR", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 27, Name = "Uttar Pradesh", StateCode = "UP", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 28, Name = "Uttarakhand", StateCode = "UK", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 29, Name = "West Bengal", StateCode = "WB", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 30, Name = "Andaman and Nicobar Islands", StateCode = "AN", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 31, Name = "Chandigarh", StateCode = "CH", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 32, Name = "Dadra and Nagar Haveli and Daman and Diu", StateCode = "DH", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 33, Name = "Delhi", StateCode = "DL", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 34, Name = "Jammu and Kashmir", StateCode = "JK", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 35, Name = "Ladakh", StateCode = "LA", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 36, Name = "Lakshadweep", StateCode = "LD", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 37, Name = "Puducherry", StateCode = "PY", CountryId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new State { Id = 38, Name = "California", StateCode = "CA", CountryId = 3, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc }
    ];

    internal static readonly District[] Districts =
    [
        new District { Id = 1, Name = "-", StateId = 1, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 2, Name = "Ariyalur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 3, Name = "Chengalpattu", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 4, Name = "Chennai", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 5, Name = "Coimbatore", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 6, Name = "Cuddalore", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 7, Name = "Dharmapuri", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 8, Name = "Dindigul", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 9, Name = "Erode", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 10, Name = "Kallakurichi", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 11, Name = "Kanchipuram", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 12, Name = "Kanyakumari", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 13, Name = "Karur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 14, Name = "Krishnagiri", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 15, Name = "Madurai", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 16, Name = "Mayiladuthurai", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 17, Name = "Nagapattinam", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 18, Name = "Namakkal", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 19, Name = "Nilgiris", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 20, Name = "Perambalur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 21, Name = "Pudukkottai", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 22, Name = "Ramanathapuram", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 23, Name = "Ranipet", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 24, Name = "Salem", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 25, Name = "Sivaganga", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 26, Name = "Tenkasi", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 27, Name = "Thanjavur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 28, Name = "Theni", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 29, Name = "Thoothukudi", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 30, Name = "Tiruchirappalli", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 31, Name = "Tirunelveli", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 32, Name = "Tirupattur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 33, Name = "Tiruppur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 34, Name = "Tiruvallur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 35, Name = "Tiruvannamalai", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 36, Name = "Tiruvarur", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 37, Name = "Vellore", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 38, Name = "Viluppuram", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 39, Name = "Virudhunagar", StateId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 40, Name = "Bengaluru Urban", StateId = 12, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 41, Name = "Ernakulam", StateId = 13, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 42, Name = "Hyderabad", StateId = 25, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 43, Name = "Mumbai Suburban", StateId = 15, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 44, Name = "New Delhi", StateId = 33, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 45, Name = "Pune", StateId = 15, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 46, Name = "Ahmedabad", StateId = 8, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 47, Name = "Jaipur", StateId = 22, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 48, Name = "Kolkata", StateId = 29, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 49, Name = "Lucknow", StateId = 27, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 50, Name = "Bhopal", StateId = 14, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 51, Name = "Khordha", StateId = 20, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 52, Name = "Visakhapatnam", StateId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 53, Name = "Mysuru", StateId = 12, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 54, Name = "Thiruvananthapuram", StateId = 13, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 55, Name = "Chandigarh", StateId = 31, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 56, Name = "Puducherry", StateId = 37, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 57, Name = "North Goa", StateId = 7, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 58, Name = "Srinagar", StateId = 34, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new District { Id = 59, Name = "Leh", StateId = 35, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc }
    ];

    internal static readonly City[] Cities =
    [
        new City { Id = 1, Name = "-", DistrictId = 1, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 2, Name = "Chennai", DistrictId = 4, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 3, Name = "Coimbatore", DistrictId = 5, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 4, Name = "Madurai", DistrictId = 15, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 5, Name = "Tiruchirappalli", DistrictId = 30, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 6, Name = "Salem", DistrictId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 7, Name = "Tiruppur", DistrictId = 33, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 8, Name = "Erode", DistrictId = 9, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 9, Name = "Vellore", DistrictId = 37, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 10, Name = "Thanjavur", DistrictId = 27, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 11, Name = "Tirunelveli", DistrictId = 31, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 12, Name = "Thoothukudi", DistrictId = 29, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 13, Name = "Hosur", DistrictId = 14, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 14, Name = "Kanchipuram", DistrictId = 11, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 15, Name = "Dindigul", DistrictId = 8, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 16, Name = "Karur", DistrictId = 13, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 17, Name = "Nagapattinam", DistrictId = 17, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 18, Name = "Nagercoil", DistrictId = 12, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 19, Name = "Bengaluru", DistrictId = 40, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 20, Name = "Kochi", DistrictId = 41, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 21, Name = "Hyderabad", DistrictId = 42, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 22, Name = "Mumbai", DistrictId = 43, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 23, Name = "New Delhi", DistrictId = 44, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 24, Name = "Pune", DistrictId = 45, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 25, Name = "Ahmedabad", DistrictId = 46, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 26, Name = "Jaipur", DistrictId = 47, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 27, Name = "Kolkata", DistrictId = 48, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 28, Name = "Lucknow", DistrictId = 49, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 29, Name = "Bhopal", DistrictId = 50, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 30, Name = "Bhubaneswar", DistrictId = 51, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 31, Name = "Visakhapatnam", DistrictId = 52, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 32, Name = "Mysuru", DistrictId = 53, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 33, Name = "Thiruvananthapuram", DistrictId = 54, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 34, Name = "Chandigarh", DistrictId = 55, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 35, Name = "Puducherry", DistrictId = 56, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 36, Name = "Panaji", DistrictId = 57, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 37, Name = "Srinagar", DistrictId = 58, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new City { Id = 38, Name = "Leh", DistrictId = 59, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc }
    ];

    internal static readonly Pincode[] Pincodes =
    [
        new Pincode { Id = 1, Code = "-", CityId = 1, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 2, Code = "600001", CityId = 2, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 3, Code = "641001", CityId = 3, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 4, Code = "625001", CityId = 4, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 5, Code = "620001", CityId = 5, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 6, Code = "636001", CityId = 6, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 7, Code = "641601", CityId = 7, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 8, Code = "638001", CityId = 8, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 9, Code = "632001", CityId = 9, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 10, Code = "613001", CityId = 10, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 11, Code = "627001", CityId = 11, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 12, Code = "628001", CityId = 12, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 13, Code = "635109", CityId = 13, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 14, Code = "631501", CityId = 14, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 15, Code = "624001", CityId = 15, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 16, Code = "639001", CityId = 16, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 17, Code = "611001", CityId = 17, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 18, Code = "629001", CityId = 18, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 19, Code = "560001", CityId = 19, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 20, Code = "682001", CityId = 20, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 21, Code = "500001", CityId = 21, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 22, Code = "400001", CityId = 22, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 23, Code = "110001", CityId = 23, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 24, Code = "411001", CityId = 24, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 25, Code = "380001", CityId = 25, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 26, Code = "302001", CityId = 26, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 27, Code = "700001", CityId = 27, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 28, Code = "226001", CityId = 28, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 29, Code = "462001", CityId = 29, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 30, Code = "751001", CityId = 30, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 31, Code = "530001", CityId = 31, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 32, Code = "570001", CityId = 32, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 33, Code = "695001", CityId = 33, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 34, Code = "160017", CityId = 34, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 35, Code = "605001", CityId = 35, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 36, Code = "403001", CityId = 36, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 37, Code = "190001", CityId = 37, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc },
        new Pincode { Id = 38, Code = "194101", CityId = 38, IsActive = true, CreatedAt = Seed.Utc, UpdatedAt = Seed.Utc }
    ];
}
